config/routes.rb
Stats::Application.routes.draw do
  resources :stats
  devise_for :users
  resources :players
  root to: 'players#index'

  

end

app/models/player.rb
class Player < ActiveRecord::Base
        fg_array = []
        ft_array = []
        tpm_array = []
        reb_array = []
        ast_array = []
        stl_array = []
        blk_array = []
        pts_array = []

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :username, :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction, :get_stats
  
  def index
    @players = Player.order(params[:sort] + " " + params[:direction])
  end
  
  # GET /players
  # GET /players.json
  def index
    @players = Player.order(params[:sort])
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :position, :fg, :ft, :tpm, :reb, :ast, :stl, :blk, :pts, :fgs)
    end

    def sort_column
   		 Player.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
         %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
    
    def get_stats
        fg_array = []
        ft_array = []
        tpm_array = []
        reb_array = []
        ast_array = []
        stl_array = []
        blk_array = []
        pts_array = []

        Player.each do |player|
          fg_array.push(player.fg)
          ft_array.push(player.ft)
          tpm_array.push(player.tpm)
          reb_array.push(player.reb)
          ast_array.push(player.ast)
          stl_array.push(player.stl)
          blk_array.push(player.blk)
          pts_array.push(player.pts)
        end
   ##     stats = []
   #     stats.push(DescriptiveStatistics::Stats.new(fg_array))
   #     stats.push(DescriptiveStatistics::Stats.new(ft_array))
   #     stats.push(DescriptiveStatistics::Stats.new(tpm_array))
   #     stats.push(DescriptiveStatistics::Stats.new(reb_array))
   #     stats.push(DescriptiveStatistics::Stats.new(ast_array))
   #     stats.push(DescriptiveStatistics::Stats.new(stl_array))
   #     stats.push(DescriptiveStatistics::Stats.new(blk_array))
   #     stats.push(DescriptiveStatistics::Stats.new(pts_array))

   #     @stats = stats
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
  		title ||= column.titleize
  		direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
  		link_to title, :sort => column, :direction => direction
	end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stats</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<h4>sparbz stats</h4>
			</div>
		</div>
	</div>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :fg %><br>
    <%= f.text_field :fg %>
  </div>
  <div class="field">
    <%= f.label :ft %><br>
    <%= f.text_field :ft %>
  </div>
  <div class="field">
    <%= f.label :tpm %><br>
    <%= f.text_field :tpm %>
  </div>
  <div class="field">
    <%= f.label :reb %><br>
    <%= f.text_field :reb %>
  </div>
  <div class="field">
    <%= f.label :ast %><br>
    <%= f.text_field :ast %>
  </div>
  <div class="field">
    <%= f.label :stl %><br>
    <%= f.text_field :stl %>
  </div>
  <div class="field">
    <%= f.label :blk %><br>
    <%= f.text_field :blk %>
  </div>
  <div class="field">
    <%= f.label :pts %><br>
    <%= f.text_field :pts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable "position" %></th>
      <th><%= sortable "fg" %></th>
      <th><%= sortable "ft" %></th>
      <th><%= sortable "tpm" %></th>
      <th><%= sortable "reb" %></th>
      <th><%= sortable "ast" %></th>
      <th><%= sortable "stl" %></th>
      <th><%= sortable "blk" %></th>
      <th><%= sortable "pts" %></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td><%= player.fg %></td>
        <td><%= player.ft %></td>
        <td><%= player.tpm %></td>
        <td><%= player.reb %></td>
        <td><%= player.ast %></td>
        <td><%= player.stl %></td>
        <td><%= player.blk %></td>
        <td><%= player.pts %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position %>
</p>

<p>
  <strong>Fg:</strong>
  <%= @player.fg %>
</p>

<p>
  <strong>Ft:</strong>
  <%= @player.ft %>
</p>

<p>
  <strong>Tpm:</strong>
  <%= @player.tpm %>
</p>

<p>
  <strong>Reb:</strong>
  <%= @player.reb %>
</p>

<p>
  <strong>Ast:</strong>
  <%= @player.ast %>
</p>

<p>
  <strong>Stl:</strong>
  <%= @player.stl %>
</p>

<p>
  <strong>Blk:</strong>
  <%= @player.blk %>
</p>

<p>
  <strong>Pts:</strong>
  <%= @player.pts %>
</p>

<p>
  <strong>FG Score:</strong>
  <%= @player.fgs %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>